paymentParams:
  port: :3000
  MID: guZEbt55224693629247
  WEBSITE: WEBSTAGING
  CHANNEL_ID: WEB
  INDUSTRY_TYPE_ID : Retail
  ORDER_ID : TEST_
  CUST_ID : Customer001
  CALLBACK_URL : http://localhost:3000/callback
  KEY: ltARhiHzhjdbU0%K
  TXNURL: https://securegw-stage.paytm.in/theia/processTransaction
  TXNSTATUSURL : https://securegw-stage.paytm.in/merchant-status/getTxnStatus
  # TXNURL: https://securegw-stage.paytm.in/order/process
  # TXNSTATUSURL : https://securegw-stage.paytm.in/order/status
database:
  host : "localhost"
  port : "5432"
  user : "postgres"
  password : "Aravipost"
  dbname : "postgres"
